version: "3.7"
services:
  wp:
    build: .
    env_file:
      - hidden.env
    labels:
      aws.ecs.fargate.deploy: 1
    ports:
      - 80:80
    links:
      - mysql
    image: 776691755094.dkr.ecr.ap-southeast-2.amazonaws.com/wordpress-boilerplate:0.0.1
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wpdb
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
